
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;



/**
 *
 * @author  tech
 */
public class BookMaster extends javax.swing.JFrame {
    MainClass mc=new MainClass();
    ResultSet rsbook;
    int rspos=0;
    int rscount=0;
    boolean chadd=false;
    /** Creates new form BookMaster */
    public BookMaster() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CmdFirst = new javax.swing.JButton();
        CmdPrevious = new javax.swing.JButton();
        CmdNext = new javax.swing.JButton();
        CmdLast = new javax.swing.JButton();
        CmdNew = new javax.swing.JButton();
        CmdEdit = new javax.swing.JButton();
        CmdSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CmdClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LblPosition = new javax.swing.JLabel();
        TxtBookID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtBookTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtAuthor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtPublisher = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtYear = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtKeywords = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CmbCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Master");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(136, 13, 30));

        CmdFirst.setBackground(new java.awt.Color(255, 255, 153));
        CmdFirst.setText("First");
        CmdFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdFirstActionPerformed(evt);
            }
        });

        CmdPrevious.setBackground(new java.awt.Color(255, 255, 153));
        CmdPrevious.setText("<<Previous");
        CmdPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdPreviousActionPerformed(evt);
            }
        });

        CmdNext.setBackground(new java.awt.Color(255, 255, 153));
        CmdNext.setText("Next>>");
        CmdNext.setPreferredSize(new java.awt.Dimension(90, 23));
        CmdNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdNextActionPerformed(evt);
            }
        });

        CmdLast.setBackground(new java.awt.Color(255, 255, 153));
        CmdLast.setText("Last");
        CmdLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdLastActionPerformed(evt);
            }
        });

        CmdNew.setBackground(new java.awt.Color(255, 255, 153));
        CmdNew.setText("New");
        CmdNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdNewActionPerformed(evt);
            }
        });

        CmdEdit.setBackground(new java.awt.Color(255, 255, 153));
        CmdEdit.setText("Edit");
        CmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdEditActionPerformed(evt);
            }
        });

        CmdSave.setBackground(new java.awt.Color(255, 255, 153));
        CmdSave.setText("Save");
        CmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdSaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 202, 70));
        jLabel1.setText(" Book Master");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(252, 202, 70)));
        jLabel1.setPreferredSize(new java.awt.Dimension(97, 20));

        CmdClose.setBackground(new java.awt.Color(255, 255, 153));
        CmdClose.setText("Close");
        CmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCloseActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(252, 202, 70));
        jLabel2.setText("Book ID:");

        LblPosition.setForeground(new java.awt.Color(252, 202, 70));
        LblPosition.setText("Book ID:");

        TxtBookID.setEditable(false);

        jLabel3.setForeground(new java.awt.Color(252, 202, 70));
        jLabel3.setText("Book Title:");

        TxtBookTitle.setBackground(new java.awt.Color(255, 255, 153));
        TxtBookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBookTitleActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(252, 202, 70));
        jLabel4.setText("Author:");

        TxtAuthor.setBackground(new java.awt.Color(255, 255, 153));

        jLabel5.setForeground(new java.awt.Color(252, 202, 70));
        jLabel5.setText("Publisher:");

        TxtPublisher.setBackground(new java.awt.Color(255, 255, 153));

        jLabel6.setForeground(new java.awt.Color(252, 202, 70));
        jLabel6.setText("Year Publish:");

        TxtYear.setBackground(new java.awt.Color(255, 255, 153));

        jLabel7.setBackground(new java.awt.Color(252, 202, 70));
        jLabel7.setForeground(new java.awt.Color(252, 202, 70));
        jLabel7.setText("Search Keyword:");

        TxtKeywords.setBackground(new java.awt.Color(255, 255, 153));
        TxtKeywords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKeywordsActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(252, 202, 70));
        jLabel8.setText("Category:");

        CmbCategory.setBackground(new java.awt.Color(255, 255, 153));
        CmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "category" }));
        CmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblPosition)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtBookID)
                                        .addComponent(TxtBookTitle)
                                        .addComponent(TxtAuthor)
                                        .addComponent(TxtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CmbCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmdLast)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdFirst)
                                .addGap(10, 10, 10)
                                .addComponent(CmdPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(CmdNew)
                                .addGap(10, 10, 10)
                                .addComponent(CmdClose))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(CmdEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CmdSave)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(TxtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addGap(84, 84, 84)
                        .addComponent(LblPosition)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdEdit)
                    .addComponent(CmdSave)
                    .addComponent(CmdLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdFirst)
                    .addComponent(CmdPrevious)
                    .addComponent(CmdNew)
                    .addComponent(CmdClose)
                    .addComponent(CmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCloseActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         MainMenu m = new MainMenu();
        m.setVisible(true);
    }//GEN-LAST:event_CmdCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        try
        {
            
            this.setLocationRelativeTo(null);
            
            ClearText();
            CmbCategory.removeAllItems();
        
            Connection connection;          
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            ResultSet rs;
            
            //fill book category
            PreparedStatement stmt=connection.prepareStatement("select * from lib_book_category order by book_category");
            rs = stmt.executeQuery();
            while (rs.next()){
                CmbCategory.addItem(rs.getString(1));
            }
            rs.close();
            
            
            //get book count
            stmt=connection.prepareStatement("select count(*) from lib_book_master");
            rs = stmt.executeQuery();
            rs.first();
            rscount=rs.getInt(1);

            //get book details
            Statement stmt1 = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sqlQuery = "select * from lib_book_master order by book_id";
            rsbook = stmt1.executeQuery(sqlQuery);
            
            //display first record
            rsbook.first();
                 
            Display();         

        }
        catch (Exception e)
        {
            System.err.println(e);
            //System.exit(1);
        }
    }//GEN-LAST:event_formWindowOpened

    private void CmdNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdNewActionPerformed
        
        chadd=true;
        ClearText();
    }//GEN-LAST:event_CmdNewActionPerformed

    private void CmdNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdNextActionPerformed
       
        try
        {
            if (rsbook.isLast()==true)
            {
                JOptionPane.showMessageDialog(null,"Already in last record.");
                return;                
                
            }
            rsbook.next();
            Display();
           
        }
        catch (Exception e)
        {
            System.err.println(e);
           
        }
    }//GEN-LAST:event_CmdNextActionPerformed

    private void CmdFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdFirstActionPerformed

        try
        {
            rsbook.first();
            Display();
            
        }
        catch (Exception e)
        {
            System.err.println(e);

        }
    }//GEN-LAST:event_CmdFirstActionPerformed

    private void CmdPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdPreviousActionPerformed

        try
        {
            if (rsbook.isFirst()==true)
            {
                JOptionPane.showMessageDialog(null,"Already in first record.");
                return;                
                
            }
            
            rsbook.previous();
            Display();
            
        }
        catch (Exception e)
        {
            System.err.println(e);

        }
    }//GEN-LAST:event_CmdPreviousActionPerformed

    private void CmdLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdLastActionPerformed
        
        try
        {
            rsbook.last();
            Display();
           
        }
        catch (Exception e)
        {
            System.err.println(e);
            //System.exit(1);
        }
    }//GEN-LAST:event_CmdLastActionPerformed

    private void CmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdEditActionPerformed
        
        chadd=false;
    }//GEN-LAST:event_CmdEditActionPerformed

    private void CmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdSaveActionPerformed

        //validate entry and save record
        try
        {

        if (TxtBookTitle.getText().trim().length()==0 )
        {
                JOptionPane.showMessageDialog(null,"Enter book title.");
                return;  
        }
        
        if (TxtAuthor.getText().trim().length()==0 )
        {
                JOptionPane.showMessageDialog(null,"Enter author.");
                return;  
        }        
        if (TxtPublisher.getText().trim().length()==0)
        {
                JOptionPane.showMessageDialog(null,"Enter publisher name.");
                return;  
        }
        if (CmbCategory.getSelectedItem().equals(""))
        {
                JOptionPane.showMessageDialog(null,"Select book category.");
                return;  
        }
         

            
        
            //String strqr="";
            Connection connection;          
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);

            if (TxtBookID.getText().trim().length()==0 )
            {
                //strqr="insert into lib_book_master (book_title, book_author, book_publisher, book_publish_year, book_category, book_keyword) values ('" + TxtBookTitle.getText() + "','" + TxtAuthor.getText() +"','"+ TxtPublisher.getText() +"','" + TxtYear.getText() + "','" + CmbCategory.getSelectedItem().toString() +"','" + TxtKeywords.getText() +"')";
                rsbook.moveToInsertRow();
                
                rsbook.updateString("book_title",TxtBookTitle.getText());
                rsbook.updateString("book_author",TxtAuthor.getText());
                rsbook.updateString("book_publisher",TxtPublisher.getText());
                rsbook.updateString("book_publish_year",TxtYear.getText());
                rsbook.updateString("book_category",CmbCategory.getSelectedItem().toString());
                rsbook.updateString("book_keyword",TxtKeywords.getText());

                rsbook.insertRow();
                
                rsbook.last();
                Display();
            }
            else
            {
                rsbook.updateString("book_title",TxtBookTitle.getText());
                rsbook.updateString("book_author",TxtAuthor.getText());
                rsbook.updateString("book_publisher",TxtPublisher.getText());
                rsbook.updateString("book_publish_year",TxtYear.getText());
                rsbook.updateString("book_category",CmbCategory.getSelectedItem().toString());
                rsbook.updateString("book_keyword",TxtKeywords.getText());

                rsbook.updateRow();
                rsbook.refreshRow();
            }
            
            
            JOptionPane.showMessageDialog(null,"Record updated.");
        }
        catch (Exception e)
        {
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"Unable to save record.");
            return; 
        }
    }//GEN-LAST:event_CmdSaveActionPerformed

    private void TxtBookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBookTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBookTitleActionPerformed

    private void TxtKeywordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKeywordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKeywordsActionPerformed

    private void CmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbCategoryActionPerformed
    
    private void Display()
    {
        try
        {
            //clear text of fields for entry/display old data
            TxtBookID.setText(rsbook.getString("book_id"));
            TxtBookTitle.setText(rsbook.getString("book_title"));
            TxtAuthor.setText(rsbook.getString("book_author"));
            TxtPublisher.setText(rsbook.getString("book_publisher"));
            TxtYear.setText(rsbook.getString("book_publish_year"));
            CmbCategory.setSelectedItem(rsbook.getString("book_category"));
            TxtKeywords.setText(rsbook.getString("book_keyword"));
            
            LblPosition.setText("Record position : " + rsbook.getRow() + "/" + String.valueOf(rscount));
        }
        catch (Exception e)
        {
            System.err.println(e);
            
        }
    }
    
    private void ClearText()
    {
        //clear text of fields for entry/display old data
        TxtBookID.setText("");
        TxtBookTitle.setText("");
        TxtAuthor.setText("");
        TxtPublisher.setText("");
        TxtYear.setText("");
        CmbCategory.setSelectedItem(null);
        TxtKeywords.setText("");
        
        LblPosition.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookMaster().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbCategory;
    private javax.swing.JButton CmdClose;
    private javax.swing.JButton CmdEdit;
    private javax.swing.JButton CmdFirst;
    private javax.swing.JButton CmdLast;
    private javax.swing.JButton CmdNew;
    private javax.swing.JButton CmdNext;
    private javax.swing.JButton CmdPrevious;
    private javax.swing.JButton CmdSave;
    private javax.swing.JLabel LblPosition;
    private javax.swing.JTextField TxtAuthor;
    private javax.swing.JTextField TxtBookID;
    private javax.swing.JTextField TxtBookTitle;
    private javax.swing.JTextField TxtKeywords;
    private javax.swing.JTextField TxtPublisher;
    private javax.swing.JTextField TxtYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
