import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author  techs
 */
public class IssueBook extends javax.swing.JFrame {
    
    /** Creates new form IssueBook */
    public IssueBook() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CmdBookDetails = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtBookStatus = new javax.swing.JTextField();
        TxtMemberID = new javax.swing.JTextField();
        TxtBookTitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CmdReset = new javax.swing.JButton();
        CmdMemberDetails = new javax.swing.JButton();
        CmdIssueBook = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CmdClose = new javax.swing.JButton();
        TxtMemberName = new javax.swing.JTextField();
        TxtMemberStatus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtBookID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Issue Book");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(136, 13, 30));

        CmdBookDetails.setBackground(new java.awt.Color(255, 255, 153));
        CmdBookDetails.setText("Details");
        CmdBookDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdBookDetailsActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(252, 202, 70));
        jLabel5.setText("Title :");

        jLabel3.setForeground(new java.awt.Color(252, 202, 70));
        jLabel3.setText("Member ID :");

        TxtBookStatus.setEditable(false);

        TxtMemberID.setBackground(new java.awt.Color(255, 255, 153));

        TxtBookTitle.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 202, 70));
        jLabel1.setText("Issue Book");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(252, 202, 70)));
        jLabel1.setPreferredSize(new java.awt.Dimension(83, 20));

        CmdReset.setBackground(new java.awt.Color(255, 255, 153));
        CmdReset.setText("Reset");
        CmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdResetActionPerformed(evt);
            }
        });

        CmdMemberDetails.setBackground(new java.awt.Color(255, 255, 153));
        CmdMemberDetails.setText("Details");
        CmdMemberDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdMemberDetailsActionPerformed(evt);
            }
        });

        CmdIssueBook.setBackground(new java.awt.Color(255, 255, 153));
        CmdIssueBook.setText("Issue Book");
        CmdIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdIssueBookActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(252, 202, 70));
        jLabel2.setText("Name :");

        CmdClose.setBackground(new java.awt.Color(255, 255, 153));
        CmdClose.setText("Close");
        CmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCloseActionPerformed(evt);
            }
        });

        TxtMemberName.setEditable(false);

        TxtMemberStatus.setEditable(false);

        jLabel4.setForeground(new java.awt.Color(252, 202, 70));
        jLabel4.setText("Book ID :");

        TxtBookID.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdReset)
                                .addGap(26, 26, 26)
                                .addComponent(CmdIssueBook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmdClose))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmdMemberDetails))
                            .addComponent(TxtMemberName)
                            .addComponent(TxtMemberStatus)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmdBookDetails))
                            .addComponent(TxtBookTitle)
                            .addComponent(TxtBookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmdMemberDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtMemberStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CmdBookDetails)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtBookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdClose)
                    .addComponent(CmdIssueBook)
                    .addComponent(CmdReset))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdResetActionPerformed
        ClearText();
}//GEN-LAST:event_CmdResetActionPerformed

    private void CmdIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdIssueBookActionPerformed
       //issue book
        try
        {
            
        
            if (TxtMemberID.getText().trim().length()==0 ) {
                JOptionPane.showMessageDialog(null,"Enter member id.");
                return;
            }
            if (TxtBookID.getText().trim().length()==0 ) {
                JOptionPane.showMessageDialog(null,"Enter member id.");
                return;
            }
            MainClass mc=new MainClass();
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);  

            String sql = "insert into lib_transaction (trn_mem_id,trn_book_id,trn_issue_dt) values (" + TxtMemberID.getText() + "," + TxtBookID.getText() + ",sysdate())";
            PreparedStatement pst=connection.prepareStatement(sql);
            pst.executeUpdate(sql);
            
            
            sql = "update  lib_book_master set book_status='Issued' where book_id=" +  TxtBookID.getText();
            pst=connection.prepareStatement(sql);
            pst.executeUpdate(sql);
            
            
            JOptionPane.showMessageDialog(null,"Book Issued");
            ClearText();
        }
        catch (Exception e) {
            System.err.println(e);
            System.exit(1);
        }

}//GEN-LAST:event_CmdIssueBookActionPerformed

    private void CmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCloseActionPerformed
        this.setVisible(false);
        MainMenu m = new MainMenu();
        m.setVisible(true);
}//GEN-LAST:event_CmdCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ClearText();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void CmdMemberDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdMemberDetailsActionPerformed
        //get member deatils
                try
        {
            //get database connection details
            MainClass mc=new MainClass();
            
             //open connection
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            String str="";
            str="select * from lib_member_master where mem_id =? ";
           PreparedStatement pst=connection.prepareStatement(str);
           pst.setString(1, TxtMemberID.getText());

           ResultSet rs;
           rs=pst.executeQuery();
           if (rs.next())
           {
               TxtMemberName.setText(rs.getString("mem_name"));

               //get mem status
                str="select * from lib_transaction where trn_mem_id =? and (trn_receive_dt is null)";
                PreparedStatement pst1=connection.prepareStatement(str);
                pst1.setString(1, TxtMemberID.getText());

                ResultSet rs1;
                rs1=pst1.executeQuery();
                if (rs1.next())
                {
                    TxtMemberStatus.setText("Book already issued.");
                    CmdIssueBook.setEnabled(false);
                    CmdBookDetails.setEnabled(false);
                }
                else
                {
                    TxtMemberStatus.setText("No book issued.");
                    CmdIssueBook.setEnabled(true);
                    CmdBookDetails.setEnabled(true);
                }
           }
           else
           {
                JOptionPane.showMessageDialog(null,"Invalid member id.");
                TxtMemberID.setText("");
                TxtMemberName.setText("");
                TxtMemberStatus.setText("");
                CmdIssueBook.setEnabled(false);
                return;
            }
           

        }
        catch (Exception e)
        {
            System.err.println(e);
            System.exit(1);
        }
 
    }//GEN-LAST:event_CmdMemberDetailsActionPerformed

    private void CmdBookDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdBookDetailsActionPerformed
        //get member deatils
                try
        {
            //get database connection details
            MainClass mc=new MainClass();
            
             //open connection
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            String str="";
            str="select * from lib_book_master where book_id =? ";
           PreparedStatement pst=connection.prepareStatement(str);
           pst.setString(1, TxtBookID.getText());

           ResultSet rs;
           rs=pst.executeQuery();
           if (rs.next())
           {
               TxtBookTitle.setText(rs.getString("book_title"));

               //get mem status
                str="select * from lib_transaction where trn_book_id =? and (trn_receive_dt is null)";
                PreparedStatement pst1=connection.prepareStatement(str);
                pst1.setString(1, TxtBookID.getText());

                ResultSet rs1;
                rs1=pst1.executeQuery();
                if (rs1.next())
                {
                    TxtBookStatus.setText("Book not available.");
                    CmdIssueBook.setEnabled(false);
                     
                }
                else
                {
                    TxtBookStatus.setText("Book available.");
                    CmdIssueBook.setEnabled(true);
                    
                }
           }
           else
           {
                JOptionPane.showMessageDialog(null,"Invalid book id.");
                TxtBookID.setText("");
                TxtBookTitle.setText("");
                TxtBookStatus.setText("");
                CmdIssueBook.setEnabled(false);
                return;
            }
           

        }
        catch (Exception e)
        {
            System.err.println(e);
            System.exit(1);
        }
    }//GEN-LAST:event_CmdBookDetailsActionPerformed
    
    private void ClearText()
    {
        TxtMemberID.setText("");
        TxtMemberName.setText("");
        TxtMemberStatus.setText("");
        
        TxtBookID.setText("");
        TxtBookTitle.setText("");
        TxtBookStatus.setText("");
        
        CmdIssueBook.setEnabled(false);
        CmdBookDetails.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdBookDetails;
    private javax.swing.JButton CmdClose;
    private javax.swing.JButton CmdIssueBook;
    private javax.swing.JButton CmdMemberDetails;
    private javax.swing.JButton CmdReset;
    private javax.swing.JTextField TxtBookID;
    private javax.swing.JTextField TxtBookStatus;
    private javax.swing.JTextField TxtBookTitle;
    private javax.swing.JTextField TxtMemberID;
    private javax.swing.JTextField TxtMemberName;
    private javax.swing.JTextField TxtMemberStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
