import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    
    
    /** Creates new form Login */
    public Login() {
        
        
        initComponents();
        
    }
    @SuppressWarnings("deprecation")
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtUserName = new javax.swing.JTextField();
        CmdOk = new javax.swing.JButton();
        CmdClose = new javax.swing.JButton();
        TxtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Integrated Library System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 348, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setText("User Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 102, 0));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        TxtUserName.setBackground(new java.awt.Color(255, 255, 153));
        TxtUserName.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        TxtUserName.setForeground(new java.awt.Color(153, 102, 0));
        TxtUserName.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 102, 0))));
        getContentPane().add(TxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 150, 22));

        CmdOk.setBackground(new java.awt.Color(255, 255, 153));
        CmdOk.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        CmdOk.setForeground(new java.awt.Color(153, 102, 0));
        CmdOk.setText("Login");
        CmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdOkActionPerformed(evt);
            }
        });
        getContentPane().add(CmdOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 90, -1));

        CmdClose.setBackground(new java.awt.Color(255, 255, 153));
        CmdClose.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        CmdClose.setForeground(new java.awt.Color(153, 102, 0));
        CmdClose.setText("Close");
        CmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCloseActionPerformed(evt);
            }
        });
        getContentPane().add(CmdClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 90, -1));

        TxtPassword.setBackground(new java.awt.Color(255, 255, 153));
        TxtPassword.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        TxtPassword.setForeground(new java.awt.Color(153, 102, 0));
        TxtPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 102, 0))));
        TxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 150, 22));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login bg(2).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 680, 340));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/872784.jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCloseActionPerformed
        // Close project
        System.exit(1);
    }//GEN-LAST:event_CmdCloseActionPerformed

    private void CmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdOkActionPerformed
        //validation

        String stru="";
        stru=TxtUserName.getText();
        
        
        String strp="";
        strp=String.valueOf(TxtPassword.getPassword());
        if (stru.isEmpty()==true)
        {
         JOptionPane.showMessageDialog(null,"Enter User Name");
         return;
        }
        
        if (strp.isEmpty()==true)
        {
         JOptionPane.showMessageDialog(null,"Enter Password");
         return;
        }
        try
        {
            //get database connection details
            MainClass mc=new MainClass();
            
             //open connection
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            String str="";
            str="select * from lib_user where user_name =? and user_password =?";
           PreparedStatement pst=connection.prepareStatement(str);
           pst.setString(1, stru);
           pst.setString(2, strp);
           ResultSet rs;
           rs=pst.executeQuery();
           if (rs.next())
           {
               MainClass.StrUser=TxtUserName.getText();
               MainMenu m=new MainMenu();
               m.setVisible(true);
               this.setVisible(false);
               
           }
           else
           {
                JOptionPane.showMessageDialog(null,"User name or password are not correct.");
                return;
            }
           

        }
        catch (Exception e)
        {
            System.err.println(e);
            System.exit(1);
        }
        
        
    }//GEN-LAST:event_CmdOkActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        if(this.getExtendedState()!=Login.MAXIMIZED_BOTH){
            this.setExtendedState(Login.MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_formWindowOpened

    private void TxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswordActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdClose;
    private javax.swing.JButton CmdOk;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    
}
