
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author techs
 */
public class MemberMaster extends javax.swing.JFrame {

    MainClass mc = new MainClass();
    ResultSet rsmem;
    int rspos = 0;
    int rscount = 0;
    boolean chadd = false;

    /**
     * Creates new form MemberMaster
     */
    public MemberMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CmdClose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ChkMemActive = new javax.swing.JCheckBox();
        TxtMobileNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LblPosition = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CmdFirst = new javax.swing.JButton();
        TxtMemID = new javax.swing.JTextField();
        CmdPrevious = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CmdNext = new javax.swing.JButton();
        TxtName = new javax.swing.JTextField();
        CmdLast = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CmdNew = new javax.swing.JButton();
        CmdEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CmdSave = new javax.swing.JButton();
        TxtEmailID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Member Master");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(136, 13, 30));

        CmdClose.setBackground(new java.awt.Color(255, 255, 153));
        CmdClose.setText("Close");
        CmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCloseActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(252, 202, 70));
        jLabel6.setText("Mobile No:");

        ChkMemActive.setBackground(new java.awt.Color(136, 13, 30));
        ChkMemActive.setForeground(new java.awt.Color(252, 202, 70));
        ChkMemActive.setText("Member Active");

        TxtMobileNo.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 202, 70));
        jLabel1.setText(" Member Master");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(252, 202, 70)));
        jLabel1.setPreferredSize(new java.awt.Dimension(96, 20));

        LblPosition.setForeground(new java.awt.Color(252, 202, 70));
        LblPosition.setText("Book ID:");

        jLabel2.setForeground(new java.awt.Color(252, 202, 70));
        jLabel2.setText("Member ID:");

        CmdFirst.setBackground(new java.awt.Color(255, 255, 153));
        CmdFirst.setText("First");
        CmdFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdFirstActionPerformed(evt);
            }
        });

        TxtMemID.setEditable(false);

        CmdPrevious.setBackground(new java.awt.Color(255, 255, 153));
        CmdPrevious.setText("<<Previous");
        CmdPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdPreviousActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(252, 202, 70));
        jLabel3.setText("Name:");

        CmdNext.setBackground(new java.awt.Color(255, 255, 153));
        CmdNext.setText("Next>>");
        CmdNext.setPreferredSize(new java.awt.Dimension(90, 23));
        CmdNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdNextActionPerformed(evt);
            }
        });

        TxtName.setBackground(new java.awt.Color(255, 255, 153));
        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        CmdLast.setBackground(new java.awt.Color(255, 255, 153));
        CmdLast.setText("Last");
        CmdLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdLastActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(252, 202, 70));
        jLabel4.setText("Address:");

        CmdNew.setBackground(new java.awt.Color(255, 255, 153));
        CmdNew.setText("New");
        CmdNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdNewActionPerformed(evt);
            }
        });

        CmdEdit.setBackground(new java.awt.Color(255, 255, 153));
        CmdEdit.setText("Edit");
        CmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdEditActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(252, 202, 70));
        jLabel5.setText("Email ID:");

        CmdSave.setBackground(new java.awt.Color(255, 255, 153));
        CmdSave.setText("Save");
        CmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdSaveActionPerformed(evt);
            }
        });

        TxtEmailID.setBackground(new java.awt.Color(255, 255, 153));

        TxtAddress.setBackground(new java.awt.Color(255, 255, 153));
        TxtAddress.setColumns(20);
        TxtAddress.setLineWrap(true);
        TxtAddress.setRows(5);
        TxtAddress.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TxtAddress);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdFirst)
                                .addGap(10, 10, 10)
                                .addComponent(CmdPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdLast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChkMemActive, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmdClose))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmdSave))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(LblPosition))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtEmailID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtMemID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtMobileNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtMemID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(LblPosition)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdLast)
                    .addComponent(CmdEdit)
                    .addComponent(CmdSave)
                    .addComponent(ChkMemActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdFirst)
                    .addComponent(CmdPrevious)
                    .addComponent(CmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmdClose)
                    .addComponent(CmdNew))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void Display() {
        try {
            //clear text of fields for entry/display old data
            TxtMemID.setText(rsmem.getString("mem_id"));
            TxtName.setText(rsmem.getString("mem_name"));
            TxtAddress.setText(rsmem.getString("mem_address"));
            TxtEmailID.setText(rsmem.getString("mem_email_id"));
            TxtMobileNo.setText(rsmem.getString("mem_mobile_no"));

            if (rsmem.getString("mem_active").equals("Y")) {
                ChkMemActive.setSelected(true);
            } else {
                ChkMemActive.setSelected(false);
            }

            LblPosition.setText("Record position : " + rsmem.getRow() + "/" + String.valueOf(rscount));
        } catch (Exception display) {
            System.err.println(display);

        }
    }

    private void ClearText() {
        //clear text of fields for entry/display old data
        TxtMemID.setText("");
        TxtName.setText("");
        TxtAddress.setText("");
        TxtEmailID.setText("");
        TxtMobileNo.setText("");

        ChkMemActive.setSelected(false);

        LblPosition.setText("");
    }
    private void CmdFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdFirstActionPerformed
        try {
            rsmem.first();
            Display();

        } catch (Exception e) {
            System.err.println(e);

        }
    }//GEN-LAST:event_CmdFirstActionPerformed

    private void CmdPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdPreviousActionPerformed
        try {
            if (rsmem.isFirst() == true) {
                JOptionPane.showMessageDialog(null, "Already in first record.");
                return;

            }

            rsmem.previous();
            Display();

        } catch (Exception e) {
            System.err.println(e);

        }
    }//GEN-LAST:event_CmdPreviousActionPerformed

    private void CmdNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdNextActionPerformed
        try {
            if (rsmem.isLast() == true) {
                JOptionPane.showMessageDialog(null, "Already in last record.");
                return;

            }
            rsmem.next();
            Display();

        } catch (Exception e) {
            System.err.println(e);

        }
    }//GEN-LAST:event_CmdNextActionPerformed

    private void CmdLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdLastActionPerformed
        try {
            rsmem.last();
            Display();

        } catch (Exception e) {
            System.err.println(e);
            //System.exit(1);
        }
    }//GEN-LAST:event_CmdLastActionPerformed

    private void CmdNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdNewActionPerformed
        chadd = true;
        ClearText();
    }//GEN-LAST:event_CmdNewActionPerformed

    private void CmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdEditActionPerformed
        chadd = false;
    }//GEN-LAST:event_CmdEditActionPerformed

    private void CmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdSaveActionPerformed

        //validate entry and save record
        try {

            if (TxtName.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Enter member name.");
                return;
            }

            if (TxtAddress.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Enter address.");
                return;
            }
            if (TxtEmailID.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Enter email id.");
                return;
            }
            if (TxtMobileNo.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Enter mobile no.");
                return;
            }

            //String strqr="";
            Connection connection;
            connection = DriverManager.getConnection(mc.StrUrl, mc.StrUid, mc.StrPwd);

            if (TxtMemID.getText().trim().length() == 0) {

                rsmem.moveToInsertRow();

                rsmem.updateString("mem_name", TxtName.getText());
                rsmem.updateString("mem_address", TxtAddress.getText());
                rsmem.updateString("mem_email_id", TxtEmailID.getText());
                rsmem.updateString("mem_mobile_no", TxtMobileNo.getText());
                //getting current date
                LocalDate dateObj = LocalDate.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                String date = dateObj.format(formatter);
                rsmem.updateString("mem_registered_date", date);
                if (ChkMemActive.isSelected() == true) {
                    rsmem.updateString("mem_active", "Y");
                } else {
                    rsmem.updateString("mem_active", "N");
                }

                rsmem.insertRow();

                rsmem.last();
                Display();
            } else {
                rsmem.updateString("mem_name", TxtName.getText());
                rsmem.updateString("mem_address", TxtAddress.getText());
                rsmem.updateString("mem_email_id", TxtEmailID.getText());
                rsmem.updateString("mem_mobile_no", TxtMobileNo.getText());

                if (ChkMemActive.isSelected() == true) {
                    rsmem.updateString("mem_active", "Y");
                } else {
                    rsmem.updateString("mem_active", "N");
                }

                rsmem.updateRow();
                rsmem.refreshRow();
            }

            JOptionPane.showMessageDialog(null, "Record updated.");
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Unable to save record.");
            return;
        }
    }//GEN-LAST:event_CmdSaveActionPerformed

    private void CmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenu m = new MainMenu();
        m.setVisible(true);
    }//GEN-LAST:event_CmdCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {

            this.setLocationRelativeTo(null);

            ClearText();

            Connection connection;
            connection = DriverManager.getConnection(mc.StrUrl, mc.StrUid, mc.StrPwd);
            ResultSet rs;

            //get mem details
            Statement stmt1 = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sqlQuery = "select * from lib_member_master order by mem_id";
            rsmem = stmt1.executeQuery(sqlQuery);

            //get mem count
            PreparedStatement stmt;
            stmt = connection.prepareStatement("select count(*) from lib_member_master");
            rs = stmt.executeQuery();
            rs.first();
            rscount = rs.getInt(1);

            //display first record
            rsmem.first();

            Display();

        } catch (Exception e) {
            System.err.println(e);
            //System.exit(1);
        }


    }//GEN-LAST:event_formWindowOpened

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChkMemActive;
    private javax.swing.JButton CmdClose;
    private javax.swing.JButton CmdEdit;
    private javax.swing.JButton CmdFirst;
    private javax.swing.JButton CmdLast;
    private javax.swing.JButton CmdNew;
    private javax.swing.JButton CmdNext;
    private javax.swing.JButton CmdPrevious;
    private javax.swing.JButton CmdSave;
    private javax.swing.JLabel LblPosition;
    private javax.swing.JTextArea TxtAddress;
    private javax.swing.JTextField TxtEmailID;
    private javax.swing.JTextField TxtMemID;
    private javax.swing.JTextField TxtMobileNo;
    private javax.swing.JTextField TxtName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
