import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author  techs
 */
public class ReceiveBook extends javax.swing.JFrame {
    
    /** Creates new form ReceiveBook */
    public ReceiveBook() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblBookID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtMemberID = new javax.swing.JTextField();
        CmdMemberDetails = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtMemberName = new javax.swing.JTextField();
        CmdReset = new javax.swing.JButton();
        CmdReceiveBook = new javax.swing.JButton();
        CmdClose = new javax.swing.JButton();
        TxtBookDetails = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Receive Book");
        setPreferredSize(new java.awt.Dimension(460, 340));
        setResizable(false);
        setSize(new java.awt.Dimension(460, 340));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LblBookID.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        LblBookID.setForeground(java.awt.Color.lightGray);

        jPanel1.setBackground(new java.awt.Color(136, 13, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(474, 402));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 202, 70));
        jLabel1.setText("Receive Book");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(252, 202, 70)));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel3.setForeground(new java.awt.Color(252, 202, 70));
        jLabel3.setText("Member ID :");

        TxtMemberID.setBackground(new java.awt.Color(255, 255, 153));

        CmdMemberDetails.setBackground(new java.awt.Color(255, 255, 153));
        CmdMemberDetails.setText("Details");
        CmdMemberDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdMemberDetailsActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(252, 202, 70));
        jLabel2.setText("Name :");

        TxtMemberName.setEditable(false);

        CmdReset.setBackground(new java.awt.Color(255, 255, 153));
        CmdReset.setText("Reset");
        CmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdResetActionPerformed(evt);
            }
        });

        CmdReceiveBook.setBackground(new java.awt.Color(255, 255, 153));
        CmdReceiveBook.setText("Receive Book");
        CmdReceiveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdReceiveBookActionPerformed(evt);
            }
        });

        CmdClose.setBackground(new java.awt.Color(255, 255, 153));
        CmdClose.setText("Close");
        CmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCloseActionPerformed(evt);
            }
        });

        TxtBookDetails.setEditable(false);

        jLabel4.setForeground(new java.awt.Color(252, 202, 70));
        jLabel4.setText("Title :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdReset)
                                .addGap(41, 41, 41)
                                .addComponent(CmdReceiveBook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmdClose))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmdMemberDetails))
                            .addComponent(TxtMemberName)
                            .addComponent(TxtBookDetails))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CmdMemberDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtBookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdReceiveBook)
                    .addComponent(CmdReset)
                    .addComponent(CmdClose))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblBookID)
                .addGap(289, 289, 289))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LblBookID))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmdMemberDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdMemberDetailsActionPerformed
        //get member deatils
        try {
            //get database connection details
            MainClass mc=new MainClass();
            
            //open connection
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            String str="";
            str="select * from lib_member_master where mem_id =? ";
            PreparedStatement pst=connection.prepareStatement(str);
            pst.setString(1, TxtMemberID.getText());
            
            ResultSet rs;
            rs=pst.executeQuery();
            if (rs.next()) {
                TxtMemberName.setText(rs.getString("mem_name"));
                
                //get mem status
                str="select * from lib_transaction, lib_book_master where book_id=trn_book_id and trn_mem_id =? and (trn_receive_dt is null)";
                PreparedStatement pst1=connection.prepareStatement(str);
                pst1.setString(1, TxtMemberID.getText());
                
                ResultSet rs1;
                rs1=pst1.executeQuery();
                if (rs1.next()) {
                    TxtBookDetails.setText("Available Book : " + rs1.getString("book_title"));
                    CmdReceiveBook.setEnabled(true);
                    LblBookID.setText(rs1.getString("book_id"));

                } else {
                    TxtBookDetails.setText("No book available.");
                    CmdReceiveBook.setEnabled(false);
                    LblBookID.setText("");
                    
                }
            } else {
                JOptionPane.showMessageDialog(null,"Invalid member id.");
                TxtMemberID.setText("");
                TxtMemberName.setText("");
                TxtBookDetails.setText("");
                CmdReceiveBook.setEnabled(false);
                LblBookID.setText("");
                return;
            }
            
            
        } catch (Exception e) {
            System.err.println(e);
            System.exit(1);
        }
    }//GEN-LAST:event_CmdMemberDetailsActionPerformed

    private void CmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdResetActionPerformed
        ClearText();
    }//GEN-LAST:event_CmdResetActionPerformed

    private void CmdReceiveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdReceiveBookActionPerformed
        //issue book
        try {
            
            
            if (TxtMemberID.getText().trim().length()==0 ) {
                JOptionPane.showMessageDialog(null,"Enter member id.");
                return;
            }

            MainClass mc=new MainClass();
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            
            String sql = "update  lib_transaction set trn_receive_dt = sysdate() where trn_mem_id= " + TxtMemberID.getText() + " and trn_receive_dt is null and trn_book_id=" + LblBookID.getText();
            PreparedStatement pst=connection.prepareStatement(sql);
            pst.executeUpdate(sql);
            
            sql = "update  lib_book_master set book_status='Available' where book_id=" + LblBookID.getText();
            pst=connection.prepareStatement(sql);
            pst.executeUpdate(sql);
            
            
            JOptionPane.showMessageDialog(null,"Book Received");
            ClearText();
        } catch (Exception e) {
            System.err.println(e);
            System.exit(1);
        }
}//GEN-LAST:event_CmdReceiveBookActionPerformed
    
    private void ClearText()
    {
        TxtMemberID.setText("");
        TxtMemberName.setText("");
        TxtBookDetails.setText("");
        LblBookID.setText("");

        CmdReceiveBook.setEnabled(false);

    }
    private void CmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCloseActionPerformed
        this.setVisible(false);
        MainMenu m = new MainMenu();
        m.setVisible(true);
    }//GEN-LAST:event_CmdCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               ClearText();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiveBook().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdClose;
    private javax.swing.JButton CmdMemberDetails;
    private javax.swing.JButton CmdReceiveBook;
    private javax.swing.JButton CmdReset;
    private javax.swing.JLabel LblBookID;
    private javax.swing.JTextField TxtBookDetails;
    private javax.swing.JTextField TxtMemberID;
    private javax.swing.JTextField TxtMemberName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
