import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author techs
 */
public class UserMaster extends javax.swing.JFrame {

    MainClass mc = new MainClass();
    ResultSet rsuser;
    int rspos = 0;
    int rscount = 0;
    boolean chadd = false;

    /**
     * Creates new form UserMaster
     */
    public UserMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CmdClose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        LblPosition = new javax.swing.JLabel();
        CmbUserType = new javax.swing.JComboBox<>();
        ChkUserActive = new javax.swing.JCheckBox();
        CmdFirst = new javax.swing.JButton();
        CmdPrevious = new javax.swing.JButton();
        CmdNext = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CmdLast = new javax.swing.JButton();
        TxtUserName = new javax.swing.JTextField();
        CmdNew = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CmdEdit = new javax.swing.JButton();
        TxtPassword = new javax.swing.JTextField();
        CmdSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Master");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(136, 13, 30));

        CmdClose.setBackground(new java.awt.Color(255, 255, 153));
        CmdClose.setText("Close");
        CmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCloseActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(252, 202, 70));
        jLabel8.setText("User Type :");

        LblPosition.setForeground(new java.awt.Color(252, 202, 70));
        LblPosition.setText("position");

        CmbUserType.setBackground(new java.awt.Color(255, 255, 153));
        CmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        ChkUserActive.setBackground(new java.awt.Color(136, 13, 30));
        ChkUserActive.setForeground(new java.awt.Color(252, 202, 70));
        ChkUserActive.setText("User Active");
        ChkUserActive.setOpaque(true);

        CmdFirst.setBackground(new java.awt.Color(255, 255, 153));
        CmdFirst.setText("First");
        CmdFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdFirstActionPerformed(evt);
            }
        });

        CmdPrevious.setBackground(new java.awt.Color(255, 255, 153));
        CmdPrevious.setText("<<Previous");
        CmdPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdPreviousActionPerformed(evt);
            }
        });

        CmdNext.setBackground(new java.awt.Color(255, 255, 153));
        CmdNext.setText("Next>>");
        CmdNext.setPreferredSize(new java.awt.Dimension(90, 23));
        CmdNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdNextActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(252, 202, 70));
        jLabel3.setText("User Name :");

        CmdLast.setBackground(new java.awt.Color(255, 255, 153));
        CmdLast.setText("Last");
        CmdLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdLastActionPerformed(evt);
            }
        });

        TxtUserName.setBackground(new java.awt.Color(255, 255, 153));

        CmdNew.setBackground(new java.awt.Color(255, 255, 153));
        CmdNew.setText("New");
        CmdNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdNewActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(252, 202, 70));
        jLabel4.setText("Password :");

        CmdEdit.setBackground(new java.awt.Color(255, 255, 153));
        CmdEdit.setText("Edit");
        CmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdEditActionPerformed(evt);
            }
        });

        TxtPassword.setBackground(new java.awt.Color(255, 255, 153));

        CmdSave.setBackground(new java.awt.Color(255, 255, 153));
        CmdSave.setText("Save");
        CmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdSaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 202, 70));
        jLabel1.setText(" User Master");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(252, 202, 70)));
        jLabel1.setPreferredSize(new java.awt.Dimension(96, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdLast)
                                .addGap(10, 10, 10)
                                .addComponent(ChkUserActive, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdFirst)
                                .addGap(10, 10, 10)
                                .addComponent(CmdPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdEdit)
                                .addGap(10, 10, 10)
                                .addComponent(CmdSave))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CmdNew)
                                .addGap(10, 10, 10)
                                .addComponent(CmdClose))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel4)))
                                .addComponent(LblPosition))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CmbUserType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(LblPosition)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdLast)
                    .addComponent(CmdEdit)
                    .addComponent(CmdSave)
                    .addComponent(ChkUserActive))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdFirst)
                    .addComponent(CmdPrevious)
                    .addComponent(CmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmdNew)
                    .addComponent(CmdClose))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmdFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdFirstActionPerformed
        try {
            rsuser.first();
            Display();

        } catch (Exception e) {
            System.err.println(e);

        }
    }//GEN-LAST:event_CmdFirstActionPerformed

    private void CmdPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdPreviousActionPerformed
        try {
            if (rsuser.isFirst() == true) {
                JOptionPane.showMessageDialog(null, "Already in first record.");
                return;

            }

            rsuser.previous();
            Display();

        } catch (Exception e) {
            System.err.println(e);

        }
    }//GEN-LAST:event_CmdPreviousActionPerformed

    private void CmdNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdNextActionPerformed
        try {
            if (rsuser.isLast() == true) {
                JOptionPane.showMessageDialog(null, "Already in last record.");
                return;

            }
            rsuser.next();
            Display();

        } catch (Exception e) {
            System.err.println(e);

        }
    }//GEN-LAST:event_CmdNextActionPerformed

    private void CmdLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdLastActionPerformed
        try {
            rsuser.last();
            Display();

        } catch (Exception e) {
            System.err.println(e);
            //System.exit(1);
        }
    }//GEN-LAST:event_CmdLastActionPerformed

    private void CmdNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdNewActionPerformed
        chadd = true;
        ClearText();
    }//GEN-LAST:event_CmdNewActionPerformed

    private void CmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdEditActionPerformed
        chadd = false;
    }//GEN-LAST:event_CmdEditActionPerformed

    private void CmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdSaveActionPerformed
        //validate entry and save record
        try {

            if (TxtUserName.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Enter user name.");
                return;
            }

            if (TxtPassword.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Enter password.");
                return;
            }

            //String strqr="";
            Connection connection;
            connection = DriverManager.getConnection(mc.StrUrl, mc.StrUid, mc.StrPwd);

            if (chadd == true) {

                rsuser.moveToInsertRow();

                rsuser.updateString("user_name", TxtUserName.getText());
                rsuser.updateString("user_password", TxtPassword.getText());
                rsuser.updateString("user_type", CmbUserType.getSelectedItem().toString());

                if (ChkUserActive.isSelected() == true) {
                    rsuser.updateString("user_active", "YES");
                } else {
                    rsuser.updateString("user_active", "NO");
                }

                rsuser.insertRow();

                rsuser.last();
                Display();
            } else {
                rsuser.updateString("user_password", TxtPassword.getText());
                rsuser.updateString("user_type", CmbUserType.getSelectedItem().toString());

                if (ChkUserActive.isSelected() == true) {
                    rsuser.updateString("user_active", "YES");
                } else {
                    rsuser.updateString("user_active", "NO");
                }

                rsuser.updateRow();
                rsuser.refreshRow();
            }

            chadd = false;
            JOptionPane.showMessageDialog(null, "Record updated.");
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Unable to save record.");
            return;
        }
    }//GEN-LAST:event_CmdSaveActionPerformed

    private void CmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenu m = new MainMenu();
        m.setVisible(true);
    }//GEN-LAST:event_CmdCloseActionPerformed

    @SuppressWarnings({"unchecked", "unchecked", "UseSpecificCatch"})
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {

            this.setLocationRelativeTo(null);

            ClearText();
            CmbUserType.removeAllItems();
            CmbUserType.addItem("Admin");
            CmbUserType.addItem("User");

            Connection connection;
            connection = DriverManager.getConnection(mc.StrUrl, mc.StrUid, mc.StrPwd);
            ResultSet rs;

            PreparedStatement stmt;
            //get user count
            stmt = connection.prepareStatement("select count(*) from lib_user");
            rs = stmt.executeQuery();
            rs.first();
            rscount = rs.getInt(1);

            //get user details
            Statement stmt1 = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sqlQuery = "select * from lib_user";
            rsuser = stmt1.executeQuery(sqlQuery);

            //display first record
            rsuser.first();

            Display();

        } catch (Exception e) {
            System.err.println(e);
            //System.exit(1);
        }

    }//GEN-LAST:event_formWindowOpened
    @SuppressWarnings("UseSpecificCatch")
    private void Display() {
        try {
            //clear text of fields for entry/display old data
            TxtUserName.setText(rsuser.getString("user_name"));
            TxtPassword.setText(rsuser.getString("user_password"));
            CmbUserType.setSelectedItem(rsuser.getString("user_type"));

            if (rsuser.getString("user_active").equals("YES")) {
                ChkUserActive.setSelected(true);
            } else {
                ChkUserActive.setSelected(false);
            }

            LblPosition.setText("Record position : " + rsuser.getRow() + "/" + String.valueOf(rscount));
        } catch (Exception e) {
            System.err.println(e);

        }
    }

    private void ClearText() {
        //clear text of fields for entry/display old data
        TxtUserName.setText("");
        TxtPassword.setText("");
        ChkUserActive.setSelected(false);

        LblPosition.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChkUserActive;
    private javax.swing.JComboBox<String> CmbUserType;
    private javax.swing.JButton CmdClose;
    private javax.swing.JButton CmdEdit;
    private javax.swing.JButton CmdFirst;
    private javax.swing.JButton CmdLast;
    private javax.swing.JButton CmdNew;
    private javax.swing.JButton CmdNext;
    private javax.swing.JButton CmdPrevious;
    private javax.swing.JButton CmdSave;
    private javax.swing.JLabel LblPosition;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
